### ISSUE TITLE
Is the action working

### ISSUE THREAD

**Issue by fballiano** [sansecio/ecomscan-github-action#3]
Hi @danslo, I was trying to [implement this action in MageOS](https://github.com/mage-os/mageos-magento2/pull/112) but I can't get it to work

I've tried setting the key in the inputs (we've out key in the secrets) but [I get](https://github.com/mage-os/mageos-magento2/actions/runs/12389752777/job/34583405364):
```
Run output=$(./ecomscan --key= --format=csv .)

No license key found, set one with -k or environment variable $ECOMSCAN_KEY.
```

And if I use the environment variable [it uses the "trial" key](https://github.com/mage-os/mageos-magento2/actions/runs/12409678781/job/34643772628?pr=112):
```
Run output=$(./ecomscan --key=trial --format=csv .)

Custom output options are not available for trial or expired licenses.
```

I've run out of ideas

**Comment by rhoerr** [comment]
This was solved, turned out to be because the action was running from a fork PR. Handled with `pull_request_target`.
